MAX_WEBDRIVER_LOADING_WAIT_ROUNDS = 5
WEBDRIVER_LOADING_WAIT_TIME = 5
KEYRING_SERVICE = 'xiami_auto_checkin'
XIAMI_LOGIN_URL = 'https://login.xiami.com/member/login'
LAST_CHECK_IN_FILE = 'last.txt'
CHECK_IN_STATUS_STUCK_THRESHOLD = 3600 * (24 + 6)  # seconds
CHECK_IN_ERROR_TIME_THRESHOLD = 3600 * 12  # seconds
DEFAULT_CHECKIN_ATTEMPT_PERIOD = 6 # hours
